apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ngf-nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
